data:
  filepath: main/src/main/resources/data.txt
  pdf:
    output:
      path: output/tickets.pdf

server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSION

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: R2dpxQ3vPrtfgF72
            client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
            client-name: Auth Server
            scope: user_info
            provider: custom-provider
            redirect-uri: http://localhost:8082/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:8081/auth/oauth/token
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            user-info-uri: http://localhost:8081/auth/user/me
            user-name-attribute: name
  data:
    mongodb:
      uri: mongodb+srv://user:1111@booking.7lhjh.mongodb.net/booking?retryWrites=true&w=majority

management:
  endpoint:
    health:
      show-details: "when_authorized"
  endpoints:
    web:
      exposure:
        include: '*'